### ISSUE TITLE
createrobot call is unreliable

### ISSUE THREAD

**Issue by sicklittlemonkey** [google/cloud-print-connector#206] opened 2016-04-05 03:51 UTC
Hi.

I'm trying to come up to speed and debug this myself, but here's what I've got so far.

Compiled both exe's with MSYS2, which was pretty straightforward.

Running "gcp-connector-util.exe init" and answering n/y/n/[name]/[code] results in:
Failed to initialize robot account: 500 Internal Server Error

As this stage I'm just wondering if anyone has this working currently.

Cheers,
Nick.

**Comment by jacobmarble** [comment] 2016-04-11 16:20
Hey Nick, did you find a solution to this error? If so, please describe it, then close this issue.

**Comment by sicklittlemonkey** [comment] 2016-04-12 06:57
No, I've been too busy - and this is quite hard for me to look at since my dev setup is very primitive and I can't debug Go yet. I grabbed an old Linux config and used that with the Windows build.

Is the util init working for you Jacob?

**Comment by sicklittlemonkey** [comment] 2016-04-13 03:42
Looks the same as #212.

I've added more info there including a capture of the failing request/response, but the problem seems to be server-side.

Hopefully you or someone else at Google can reproduce it.

Cheers,
Nick.

**Comment by sicklittlemonkey** [comment] 2016-04-15 03:18
Hi Jacob. Did you have a chance to look at #212?

> The question where it asked for email to share with, it cannot be the same email you will be logging in to in your browser. In other words, you cannot be sharing the printer with yourself.

Is this restriction intentional?

**Comment by jacobmarble** [comment] 2016-04-15 05:25
Sounds like the server doesn't like the idea that you're sharing with yourself. The connector doesn't check this input, just passes it along the the cloud service.

If you don't want to automatically share printers, then answer "no" to the `gcp-connector-util init` question "Retain the user OAuth token to enable automatic sharing?" This will cause the next prompt to be skipped, "User or group email address to share with:"

Does that make sense?

**Comment by sicklittlemonkey** [comment] 2016-04-15 06:24
It would make sense if it that work-around worked for me on Windows. ; - ) That's what I tried in my first post above. I just double-checked again now; same error.

I did have the problem at least once on Ubuntu when I first tried to set up the connector, because I happened to keep the Fiddler log that I posted in #212. Anyway, the Windows problem seems to be something else.

**Comment by jenden0** [comment] 2016-04-19 13:07
Using linux version I'm getting the same error regardless of my answer to the "Retain the user OAuth token..." question.  Trying a different email address in the sharing question didn't help either.

**Comment by stuarta0** [comment] 2016-04-25 09:01
Something must've changed a month ago because my printer has dropped off and I can't reconnect it. Answering no to "retain oauth" or entering a different email both don't work.  Ubuntu 14.04 Server using 2015.10.05 release.  Will update to latest release to see what happens.

**Comment by whizzzkid** [comment] 2016-04-26 12:31
All responses from the server are now: **Failed to initialize robot account: 500 Internal Server Error**

No matter what you answer in the init script, it would generate the auth code fine, but would end with the error. :-/

This is frustrating.

**Comment by jay0lee** [comment] 2016-04-26 13:26
I tried to reproduce this error but was unable. Can you provide full steps to reproduce? What Windows version are you on? What choices are you making (full output of gcp-connector-util would be good). What type of Google account are you using (Google Apps, gmail.com?)

Jay

**Comment by whizzzkid** [comment] 2016-04-26 16:22
Hi @jay0lee 

I am following this guide https://github.com/google/cups-connector/wiki/Installing-on-Raspberry-Pi-Raspbian-Jessie to set this up on my RPi. So I am on linux. I have done this a week before, but had to set this up on another machine. Last week it was not accepting googlegroups.com email ids. This week it has been just returning 500 errors on init.

No matter what combination you select, it returns a 500. Something seriously is wrong.

**Comment by jay0lee** [comment] 2016-04-26 16:26
You can't share printers with @googlegroups.com groups, only Google Apps for Business Groups so that explains the first issue. I'll try on my RPi and see if I can repro the 500 errors.

**Comment by sicklittlemonkey** [comment] 2016-04-26 22:37
Today it worked fine for me on Windows for the first time. And a second time.

It has always failed before - probably a dozen times since I logged this issue.

**Comment by whizzzkid** [comment] 2016-04-27 03:08
@jay0lee 

The googlegroup issues is a separate one. The robot account fails for other gmail addresses too. Also it fails if we disable automatic sharing.

The fun part is, once the config.json is generated, we can change the scope attribute to googlegroups.com email id and it works without a hiccup. so what's the point of disabling it in the init script?

After almost on the 21st try last night, The robot account thing worked. I did not retry because I did not want to spend 20 more tries on that. Not sure if the server is still erring or not.

**Comment by sicklittlemonkey** [comment] 2016-04-27 03:37
I'm convinced it's a server-side problem. The client is simple and has pretty static behaviour.

If the API is going to be this flakey then perhaps the client should have a retry option for robot account creation. After seeing the activity here today I actually added a loop to that with debugging to test it, but it worked first time (ever)!

**Comment by sicklittlemonkey** [comment] 2016-04-27 22:21
Ok, this morning I got what I had hoped for: what I think is proof that it's a server-side problem, and a possible work-around in the client: just loop till it works.

Here's the log from my first test run this morning. I had added some extra logging and a loop with a 5-second sleep. It succeeded on the 4th attempt at 10:12 am 28th April NZT (if anyone has access to server-side logs).
```
Cloud Print Connector.info(3): Calling createrobot
Cloud Print Connector.error(1): Failed to initialize robot account (1): 500 Internal Server Error

Cloud Print Connector.info(3): Decoding response
Cloud Print Connector.error(1): invalid character '<' looking for beginning of value
Cloud Print Connector.error(1): Failed to initialize robot account (2):

Cloud Print Connector.info(3): Calling createrobot
Cloud Print Connector.error(1): Failed to initialize robot account (1): 500 Internal Server Error

Cloud Print Connector.info(3): Decoding response
Cloud Print Connector.error(1): invalid character '<' looking for beginning of value
Cloud Print Connector.error(1): Failed to initialize robot account (2):

Cloud Print Connector.info(3): Calling createrobot
Cloud Print Connector.error(1): Failed to initialize robot account (1): 500 Internal Server Error

Cloud Print Connector.info(3): Decoding response
Cloud Print Connector.error(1): invalid character '<' looking for beginning of value
Cloud Print Connector.error(1): Failed to initialize robot account (2):

Cloud Print Connector.info(3): Calling createrobot
Cloud Print Connector.info(3): Decoding response
Cloud Print Connector.info(3): Got success
Acquired OAuth credentials for robot account

The config file C:\msys64\home\nickw\gcp-windows-connector.config.json is ready to rock.
Keep it somewhere safe, as it contains an OAuth refresh token.

```

**Comment by whizzzkid** [comment] 2016-04-28 02:46
@sicklittlemonkey looks about right, Thanks :+1:  the server is not always in the mood! :smile:

**Comment by sicklittlemonkey** [comment] 2016-05-06 02:22
@jacobmarble 
So ... I could submit a pull request but it seems trivial. (Plus would I need more direction on what the preferred solution is if not to print retry messages while looping forever.)

**Comment by jacobmarble** [comment] 2016-05-08 22:18
Go ahead with the pull request. I'm very short on time right now, but I
always have time to review pull requests.

**Comment by sicklittlemonkey** [comment] 2016-05-12 04:35
@jacobmarble 
I've thrown my pull request in the hat too, since it was done and tested.

**Comment by agoode** [comment] 2016-06-07 02:36
/createrobot is a bit weird, since it is an undocumented API. I'm a bit new to this project so I don't know the history here.

Maybe there is a better API than /createrobot to use? It looks like chromium uses it too though:
https://chromium.googlesource.com/chromium/src/+/master/chrome/common/cloud_print/cloud_print_helpers.cc#175

/createrobot might be buggy on the server side, I'll try to see who I can ping about that.

**Closed** 2016-06-15 20:04 UTC
