### ISSUE TITLE
Windows service connector support

### ISSUE THREAD

**Issue by sabbadino** [google/cloud-print-connector#446] opened 2019-04-04 05:13 UTC
Hi, I see that the last release of the connector has been done 1 year ago. Is this project still active ? 
I played with the windows service and compared it to the chrome built in one.
The chrome connector does see network printers while the one in the windows service does not. I managed to have a network printer seen when installed as if it was a  local one (a kind of trick you do in windows), in this way the service did see the printer , but it prints garbage. With an actual local USB printer it does work fine.

Any comment from Google on the matter ? 
Thank you.
Enrico ok

**Comment by jay0lee** [comment] 2019-04-08 15:54
This seems to be a duplicate of #437

**Closed by jay0lee** 2019-04-08 15:54 UTC

**Comment by sabbadino** [comment] 2019-04-08 16:13
As i said, when I install the network printer as a local one, it seems working (printer is registered by the gcp connector service), but it prints out garbage or blank pages when I try to print from a program I wrote that calls the print API.
However the same program prints the same document fine when I try to print from the chrome cloud print page. Could it be I am not crafting the print ticket properly ? (When I print to a local printer , using the same print ticket , it does work fine).
